---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "9.0"
cache:
  directories:
    - node_modules
install:
  - yarn
before_script:
  - export CI=false
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./static/
  domain: burfield-nightlife.surge.sh